name: ci-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      - run: pytest
  build:
    needs: [run-test-code]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      
      - name: Image Build
        run: docker build -t goguma1/flaskweb:latest .
      - name: Image Display
        run: docker images
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: goguma1
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Image Push
        run: docker push goguma1/flaskweb:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_USERNAME: goguma1
          DOKCER_REPO: flaskweb
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN}}
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_SSH_KEY}}
          envs: DOCKER_USERNAME, DOKCER_REPO, DOCKER_TOKEN
          debug: true
          time: 30s